"""updated validations on book and rating table

Revision ID: b2968f61f98b
Revises: aad74ea4d178
Create Date: 2023-07-27 23:37:45.137800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2968f61f98b'
down_revision = 'aad74ea4d178'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_unique_constraint(None, 'books', ['isbn'])
    op.alter_column('ratings', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ratings', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'review_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('ratings_book_id_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_book_id_fkey', 'ratings', 'books', ['book_id'], ['id'])
    op.alter_column('ratings', 'review_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ratings', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ratings', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ratings', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'books', type_='unique')
    op.alter_column('books', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('books', 'isbn',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
